version: 2

jobs:
  build-linux-ghc-bindist:
    docker:
      - image: debian
    working_directory: ~/rules_haskell
    resource_class: large
    steps:
      - checkout
      - run:
          name: Install Bazel
          command: |
            apt-get update
            apt-get install -y curl gnupg golang make libgmp3-dev
            echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list
            curl https://bazel.build/bazel-release.pub.gpg | apt-key add -
            apt-get update
            apt-get install -y bazel
      - run:
          name: Build tests
          command: |
            bazel build --config ci //tests/binary-simple

  # ATTN: when you change anything here, don’t forget to copy it to the build-darwin section
  build-linux-nixpkgs:
    docker:
      - image: nixos/nix:2.1.3
    working_directory: ~/rules_haskell
    resource_class: large
    steps:
      - checkout
      - run:
          name: System dependencies
          command: |
            apk --no-progress update
            apk --no-progress add bash ca-certificates
            nix-channel --update
            # CircleCI and Nix sandboxing don't play nice. See
            # https://discourse.nixos.org/t/nixos-on-ovh-kimsufi-cloning-builder-process-operation-not-permitted/1494/5
            mkdir -p /etc/nix && echo "sandbox = false" > /etc/nix/nix.conf
      - run:
          name: Configure
          command: |
            echo "build:ci --host_platform=@io_tweag_rules_haskell//haskell/platforms:linux_x86_64_nixpkgs" > .bazelrc.local
      - run:
          name: Build tests
          command: |
            nix-shell --arg docTools false --pure --run \
              'bazel build --config ci //tests/...'
      - run:
          name: Run tests
          # bazel does not support recursive bazel call, so we
          # cannot use bazel run here because the test runner uses
          # bazel
          command: |
            nix-shell --arg docTools false --pure --run \
              'bazel build --config ci //tests:run-tests'
            nix-shell --arg docTools false --pure --run \
              './bazel-ci-bin/tests/run-tests'

  build-darwin:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Install Nix
          command: |
            curl https://nixos.org/nix/install | sh
      - run:
          name: Configure
          command: |
            echo "build:ci --host_platform=@io_tweag_rules_haskell//haskell/platforms:darwin_x86_64_nixpkgs" > .bazelrc.local
      - run:
          name: Build tests
          shell: /bin/bash -eilo pipefail
          command: |
            nix-shell --arg docTools false --pure --run \
              'bazel build --config ci //tests/...'
      - run:
          name: Run tests
          shell: /bin/bash -eilo pipefail
          command: |
            nix-shell --arg docTools false --pure --run \
              'bazel build --config ci //tests:run-tests'
            # XXX 2019-01-22 Disable start script checking on Darwin
            # due to a clash between binutils and clang.
            nix-shell --arg docTools false --pure --run \
              './bazel-ci-bin/tests/run-tests --skip "/startup script/"'

workflows:
  version: 2
  build:
    jobs:
      - build-linux-ghc-bindist
      - build-linux-nixpkgs
      - build-darwin
